---

- name: SCAP Security Evaluation
  hosts: all

  tasks:
    - name: Installing SCAP Security Guide
      yum: name=scap-security-guide state=latest

    - name: Executing oscap command and publishing the report at http://{{ ansible_eth0.ipv4.address }}
      command: "oscap xccdf eval \
	--profile xccdf_org.ssgproject.content_profile_pci-dss \
	--report /var/www/html/index.html \
	/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"

      ignore_errors: True
