---
- name: Restore VM from snap
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
#    username:
#    url:
#    password:
    datacenter: DomoDC
    cluster: DemoLab
    template: host3-template
    vm_name: test01
    user_name: jacek

  tasks:
#  - name: Obtain SSO token
#    ovirt_auth:
#      url: "{{ url }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      insecure: yes

  - name: Stop VM
    ovirt_vm:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm }}"
      state: stopped
      wait: yes

#  - name: facts
#    setup:

  - name: Snapshot id register
    ovirt_snapshot_info:
#      auth: "{{ ovitr_auth }}"
      vm: "{{ vm }}"
      description: Initial_snap

  - name: snap debug
    debug:
      var: ovirt_snapshots

  - name: snap 2 debug
    debug:
      var: ovirt_snapshots[0].id

  - name: Restore from snap
    ovirt_snapshot:
#      auth: "{{ ovirt_auth }}"
      vm_name: "{{ vm }}"
      state: restore
      snapshot_id: "{{ ovirt_snapshots[0].id }}"
      wait: yes

  - name: Start VM
    ovirt_vm:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm }}"
      state: running
      wait: yes
