---
- name: Restore VM from snap
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
#    username:
#    url:
#    password:
    datacenter: DomoDC
    cluster: DemoLab
    template: host3-template
    vm_name: test01
    user_name: jacek

  tasks:
#  - name: Obtain SSO token
#    ovirt_auth:
#      url: "{{ url }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      insecure: yes

  - name: Stop VM
    ovirt_vm:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      state: stopped
      wait: yes

  - name: Snapshot id register
    ovirt_snapshot_info:
#      auth: "{{ ovitr_auth }}"
      vm: "{{ vm_name }}"
      description: Initial_snap
    register: results

#  - name: snap debug
#    debug:
#      var: results.ovirt_snapshots
#
#  - name: snap 2 debug
#    debug:
#      var: results.ovirt_snapshots[0].id

  - name: Restore from snap
    ovirt_snapshot:
#      auth: "{{ ovirt_auth }}"
      vm_name: "{{ vm_name }}"
      state: restore
      snapshot_id: "{{ results.ovirt_snapshots[0].id }}"
      wait: yes

  - name: Start VM
    ovirt_vm:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      state: running
      wait: yes
