---
- name: Provision VM from template
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
#    username:
#    url:
#    password:
    datacenter: MicroLab
    cluster: MicroCluster
    template: host3-template
    vm_memory: 1GiB
    vm: test02
    user_name: user20

  tasks:
#  - name: Obtain SSO token
#    ovirt_auth:
#      url: "{{ url }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      insecure: yes

  - name: Create and run VM from template
    ovirt_vms:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      description: "{{user_name}}"
      state: stopped
      wait: yes

  - name: Create initial snap
    ovirt_snapshots:
#      auth: "{{ ovirt_auth }}"
      vm_name: "{{ vm }}"
      wait: yes
      state: present
      description: Initial_snap

  - name: Start vm
    ovirt_vms:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm }}"
      state: running
      wait: yes
#    register: newvm

  - name: Pause after VM creates
    pause:
      seconds: 40

#  - name: Revoke the SSO token
#    ovirt_auth:
#      state: absent
#      ovirt_auth: "{{ ovirt_auth }}"
